baseURL: "https://www.sdlinks.net"
title: Neo VRAINS
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

menu:
  main:
    - name: Search
      url: /search/
      weight: 1
    - name: Archives
      url: /archives/
      weight: 4
    - name: Tags
      url: /tags/
      weight: 2
    - name: Categories
      url: /categories/
      weight: 3

googleAnalytics: G-RH029G1TZ5

minify:
  disableXML: true
  minifyOutput: true

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

pagination:
  disableAliases: false
  pagerSize: 8
  path: page

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
  keys: ["title", "tags", "permalink", "summary", "content", "categories"]

params:
  env: production
  title: "Neo VRAINS"
  description: "Christophe's blog site"
  author: Christophe
  ShowReadingTime: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  defaultTheme: auto
  disableThemeToggle: false
  disableSpecial1stPost: false
  math: true
  comments: true
  hideAuthor: true
  searchHidden: true

  assets:
    favicon: "images/favicon.ico"
    favicon16x16: "images/favicon-16x16.png"
    favicon32x32: "images/favicon-32x32.png"
    apple_touch_icon: "images/apple-touch-icon.png"
  #     safari_pinned_tab: "<link / abs url>"

  label:
    text: "Neo VRAINS"

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    # imageUrl: '<img location>'
    # imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "I'm Christophe"
    Content: Welcome to my blog

  socialIcons:
    - name: email
      url: "mailto:hey_christophe@outlook.com"
    - name: github
      url: "https://github.com/Christophe1997"
    - name: rss
      url: "/index.xml"

  analytics:
    google:
      SiteVerificationTag: "Neo VRAINS"
