# config.toml

baseURL = "https://christophe1997.github.io"
title = "CastOff"
theme = "hugo-primer"
languageCode = "zh-cn"
# If you are using Chinese, Japanese, or Korean, I highly recommend you to set this true.
hasCJKLanguage = true
summaryLength = 70
# Code pen
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = ""

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy;Christophe"

[frontmatter]
# update sitemap.xml's lastmod datetime by file change time, instead of git.
lastmod = ["lastmod", ":fileModTime", ":default"]

[params]
description = ""
# You can use favicon by addin them manually.
useIcon = true
# Use MathJax.js. Disabling site-wide and you still can enable in indivisual pages
math = true

shareTo = []
showFooterCredits = true

[markup]
  [markup.highlight]
    lineNoStart = 1
    lineNos = true
