baseURL: "https://christophe1997.github.io"
title: CastOff
paginate: 8
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

menu:
  main:
    - name: Archives
      url: /archives/
      weight: 10
    - name: Tags
      url: /tags/
      weight: 5
    - name: Categories
      url: /categories/
      weight: 7


googleAnalytics: UA-112755173-3

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production
    title: CastOff
    description: "Christophe's blog site"
    author: Christophe 
    ShowReadingTime: true
    ShowShareButtons: true 
    comments: false
    defaultTheme: auto
    disableThemeToggle: false
    disableSpecial1stPost: false
    math: true

    assets:
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "CastOff"
    
    

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        # imageUrl: '<img location>'
        # imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "I'm Christophe"
        Content: Welcome to my blog

    socialIcons:
        - name: email
          url: hey_christophe@outlook.com
        - name: github
          url: "https://github.com/Christophe1997"

    analytics:
        google:
            SiteVerificationTag: "CastOff"